/**
 * useMarketData — Hook for accessing coin market data
 *
 * Loads real data from public/data/market_data.json (generated by export_json.py).
 * Falls back to generated data if JSON not available.
 *
 * All components consume this hook — changing the data source here
 * updates the entire app automatically.
 */

import { useState, useEffect, useMemo, useCallback } from "react";
import { COIN_DATA, COIN_META, getLatestSnapshot, ONCHAIN_DATA, dataReady } from "../data/mockData";

export function useMarketData(selectedCoins = ["BTC", "ETH", "SOL"]) {
  const [ready, setReady] = useState(false);

  useEffect(() => {
    dataReady.then(() => setReady(true));
  }, []);

  const snapshots = useMemo(
    () => ready ? selectedCoins.map(getLatestSnapshot).filter(Boolean) : [],
    [selectedCoins, ready]
  );

  const getHistory = useCallback((symbol, days = null) => {
    const data = COIN_DATA[symbol] || [];
    if (!days) return data;
    return data.slice(-days);
  }, [ready]);

  const getOnChain = useCallback((symbol) => ONCHAIN_DATA[symbol] || null, []);

  const availableCoins = Object.keys(COIN_META);

  return { snapshots, getHistory, getOnChain, availableCoins, coinMeta: COIN_META, ready };
}
